### ISSUE TITLE
Project descriptions aren't formatted properly

### ISSUE THREAD

**Issue by qwertyasdef** [kalettuce/TeamUp#18]
https://team-up-de57f.web.app/projects/2
![image](https://user-images.githubusercontent.com/10069786/119054225-21422b80-b97c-11eb-9b23-90497a25cc48.png)
The description should have line breaks in the list of requirements, but it doesn't.

**Comment by burnhc** [comment]
![image](https://user-images.githubusercontent.com/53025754/119245802-cef63b80-bb30-11eb-827f-b82e7d7f671d.png)
