### ISSUE TITLE
Nonexistent pages are blank instead of 404

### ISSUE THREAD

**Issue by qwertyasdef** [kalettuce/TeamUp#19]
https://team-up-de57f.web.app/asdfasdfasdf
![image](https://user-images.githubusercontent.com/10069786/119054342-50f13380-b97c-11eb-83fc-c305aa48cccb.png)
There should be some kind of 404 page here so users don't get confused.

**Comment by burnhc** [comment]
Okay; for now, I just made any 404 redirect back to the landing page. Creating a separate 404 page can be an easy detail to add towards the end.

**Comment by burnhc** [comment]
### Resolved
![image](https://user-images.githubusercontent.com/53025754/119299086-2076f700-bc13-11eb-9dfb-b22af4903212.png)

**Comment by burnhc** [comment]
404 redirect works for exact paths but not with path parameters; need to add redirects when a project id or user id could not be found
